name: practica1-samuelbeteta

services:
  db:
    image: postgres:16-alpine
    container_name: practica1_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h 127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - appnet

  app:
    build: .
    container_name: practica1_expressapi
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: npm run dev
    networks:
      - appnet

networks:
  appnet:

volumes:
  db_data:
  node_modules:
